events { worker_connections 1024; }

http {
    # Upstream definition with primary and backup server nodes
    upstream multicloud_backend {
        # AWS Primary Target (active)
        server 3.138.36.196:5000 max_fails=2 fail_timeout=5s;
        
        # GCP Secondary Target (backup failover)
        server multi-cloud-gcp-secondary-kuul5kyk3q-uc.a.run.app:443 backup;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://multicloud_backend;
            proxy_set_header Host $proxy_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_server_name on;
        }
    }
}
